select * from emp;
SELECT COUNT(*) FROM EMP;

--Getting the employees who all are working in dept 20
select * from emp where deptno = 20;
--Getting the count of employees who are working in dept 20
select count(*) from emp where deptno = 20;

--Getting the employee details who are managers
select * from emp where job = 'MANAGER';

--Special Operators
--1. Like - WILD CARD CHARACTERS ARE %, _
--"%" : STANDS FOR ANY NUMBER OF CHARACTERS
--"_" : STANDS FOR A SINGLE CHARACTER
--Q. GETTING THE EMPLOYEE DETAILS WHOSE NAME STARTS WITH S
SELECT * FROM EMP WHERE ENAME LIKE 'S%';
--Q. GETTING THE EMPLOYEE DETAILS WHOSE 3RD CHARACTER SHOULD BE 'A'
SELECT * FROM EMP WHERE ENAME LIKE '__A%';
--GETTING THE EMPLOYEE DETAILS WHOSE SECOND LAST CHARACTER IS 'E'
SELECT * FROM EMP WHERE ENAME LIKE '%E_';
--GETTING ENAME, JOB, SAL EMPLOYEE DETAILS WHOSE NAME'S 1ST CHARACTER SHOULD 'J' AND SECOND LAST CHARACTER SHOULD BE 'E'
SELECT ENAME, JOB, SAL FROM EMP WHERE ENAME LIKE 'J%E_';

--2. IN : IT'S USED TO FETCH VALUES WITH SINGLE CONDITION WITH MULTIPLE VALUES
--Q. GETTING EMPLOYEE DETAILS WHO ARE WORKING IN DEPT 10 OR 20
SELECT * FROM EMP WHERE deptno = 10 OR DEPTNO = 20;
--USING IN OPERATOR
SELECT * FROM EMP WHERE DEPTNO IN(10,20);
--Q. GETTING THE EMPLOYEES WHO ARE WORKING AS CLERK OR ANALYST
SELECT * FROM EMP WHERE JOB IN('CLERK','ANALYST');

--3. BETWEEN: GETTING THE DATA FROM A SPECIFIC RANGE
--Q. GETTING THE EMPLOYEE DETAILS WHO ARE GETTING IN BETWEEN 1000 TO 3000
SELECT * FROM EMP WHERE SAL>=1000 AND SAL<=3000;
SELECT * FROM EMP WHERE SAL BETWEEN 1000 AND 3000;


--RELATIONAL OPERATORS
-- EQUALS: "="
-- GREATER THAN : ">"
-- GREATER THAN AND EQUALS: ">="
-- LESS THAN: "<"
-- LESS THAN AND EQUALS: "<="
-- NOT EQUALS: "!=" OR "<>" OR "^="
--Q. GETTING THE EMPLOYEE DETAILS WHOSE SAL NOT EQUALS TO 3000
SELECT * FROM EMP WHERE SAL<>3000;

--3. LOGICAL OPERATORS: AND, OR, NOT
--Q. Employee details where ename not starting with 'S'
select * from emp where ename not like 'S%';

--4. Arithmatic Operator
-- "+"
-- "-"
-- "*"
-- "/"
-- Q. ADD 1000 TO EMPLOYEE SALARY AND DISPLAY IT
SELECT * FROM EMP WHERE SAL=SAL+1000; -- SUSHREE, PRIYANKA
SELECT SAL, SAL+1000 UPDATEDSAL FROM EMP;
SELECT SAL FROM EMP;--MUNU
UPDATE EMP SET SAL=SAL+1000;-- NOT REQUIRED AT THIS MOMENT

--5.SET
--A. UNION - RETURNS VALUES FROM BOTH THE TABLE WITHOUT DUPLICATES
--B. UNION ALL - RETURNS VALUES FROM BOTH THE TABLE WITH DUPLICATES
--C. INTERSECT - RETURNS THE COMMON VALUES FROM BOTH THE TABLE 
--D. MINUS - RETURNS VALUES FROM THE FIRST TABLE WHICH ARE NOT PRESENT IN SECOND TABLE
SELECT * FROM STUDENT, LIB;
SELECT ID, SNAME FROM STUDENT UNION SELECT ID, SNAME FROM LIB;
SELECT ID, SNAME FROM STUDENT UNION ALL SELECT ID, SNAME FROM LIB;
SELECT ID, SNAME FROM STUDENT INTERSECT SELECT ID, SNAME FROM LIB;
SELECT ID, SNAME FROM STUDENT MINUS SELECT ID, SNAME FROM LIB;
SELECT ID, SNAME FROM LIB MINUS SELECT ID, SNAME FROM STUDENT;